name: Build and Test Arachne OS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential nasm gcc qemu-system-x86 gdb

    - name: Build the bootloader
      run: make

    - name: Run bootloader in QEMU
      run: make run

    - name: Debug bootloader with QEMU
      run: make debug
      if: ${{ always() }}

    - name: Clean build artifacts
      run: make clean
